baseURL = 'https://imgaryjiang.com/'
languageCode = 'en-us'
title = 'Gary Jiang'
theme = 'smol'

# Parameters
[params]
subtitle = "Full Stack Developer w/ a bg in Growth Marketing 📈 + Creative 🎨"
dateFmt = "01.02.2006"

# HTML
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

# Header
# [menu]
#   [[menu.main]]
#         identifier = "posts"
#         name = "Posts"
#         url = "/posts/"
#         weight = 1 

#   [[menu.main]]
#         identifier = "categories"
#         name = "Categories"
#         url = "/categories/"
#         weight = 2 

#   [[menu.main]]
#         identifier = "tags"
#         name = "Tags"
#         url = "/tags/"
#         weight = 3

# Footer
[[menu.footer]]
name = "Github"
url = "https://github.com/garysbot"
weight = 1

[[menu.footer]]
name = "LinkedIn"
url = "https://linkedin.com/in/garyjiang"
weight = 2
